### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by woyaowenzi** [Kaijun/hexo-theme-huxblog#11]
报个 BUG
```java
Unhandled rejection TypeError: /Users/baidu/Documents/opensource/blog/themes/huxblog/layout/layout.ejs:9
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>
 >> 9|           <%- partial('_partial/sidebar', null, {cache: !config.relative_link}) %>
    10|         <% } %>
    11|       </div>
    12|       <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>

/Users/baidu/Documents/opensource/blog/themes/huxblog/layout/_partial/sidebar.ejs:2
    1| <aside id="sidebar"<% if (theme.sidebar === 'bottom'){ %> class="outer"<% } %>>
 >> 2|   <% theme.widgets.forEach(function(widget){ %>
    3|     <%- partial('_widget/' + widget) %>
    4|   <% }) %>
    5| </aside>

Cannot read property 'forEach' of undefined
    at eval (eval at <anonymous> (/Users/baidu/Documents/opensource/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:185)
    at eval (eval at <anonymous> (/Users/baidu/Documents/opensource/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:342)
    at null._compiledSync (/Users/baidu/Documents/opensource/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15)
    at View.renderSync (/Users/baidu/Documents/opensource/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at /Users/baidu/Documents/opensource/blog/node_modules/hexo/lib/plugins/helper/partial.js:38:21
    at Object.fragmentCache (/Users/baidu/Documents/opensource/blog/node_modules/hexo/lib/plugins/helper/fragment_cache.js:9:30)
    at Object.wrapper [as fragment_cache] (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/lodash/lodash.js:4436:19)
    at Object.partial (/Users/baidu/Documents/opensource/blog/node_modules/hexo/lib/plugins/helper/partial.js:37:19)
    at Object.wrapper (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/lodash/lodash.js:4436:19)
    at eval (eval at <anonymous> (/Users/baidu/Documents/opensource/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:443)
    at eval (eval at <anonymous> (/Users/baidu/Documents/opensource/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:890)
    at null._compiledSync (/Users/baidu/Documents/opensource/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15)
    at tryCatcher (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at null._compiled (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at View.render (/Users/baidu/Documents/opensource/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/baidu/Documents/opensource/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/baidu/Documents/opensource/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Kaijun** [comment]
请问你是否弄错了主题, 该主题没有 /layout/_partial/sidebar.ejs: 这个文件

**Comment by yisongbetter** [comment]
遇到了同样的问题，请问是如何解决的？

**Comment by dwj999** [comment]
楼主解决了没
