### ISSUE TITLE
body is not defined when create a new page

### ISSUE THREAD

**Issue by lgyjg** [Kaijun/hexo-theme-huxblog#12]
我在创建一个新页面时使用 hexo new page Gallery 命令，想创建一个新的页面，但是在创建完成后，执行hexo g 时，报出以下异常：

Unhandled rejection ReferenceError: /home/****/blog/test/themes/huxblog/layout/page.ejs:73
 >   71|             ">
    72|             
\>\> 73|                 <%- body % >
    74|             </div>
    75|     
    76|             <div class="

body is not defined
    at eval (eval at <anonymous> (/home/×××/blog/test/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:3387)
    at eval (eval at <anonymous> (/home/×××/blog/test/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:11625)
    at null._compiledSync (/home/×××/blog/test/node_modules/ejs/lib/ejs.js:255:15)
    at tryCatcher (/home/×××/blog/test/node_modules/bluebird/js/release/util.js:16:23)
    at null._compiled (/home/×××/blog/test/node_modules/bluebird/js/release/method.js:15:34)
    at View.render (/home/×××/blog/test/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/×××/blog/test/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/×××/blog/test/node_modules/bluebird/js/release/util.js:16:23)
    at /home/×××/blog/test/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/×××/blog/test/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:726:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)

我尝试者去解决，但是没能完成。我看到了commit id为e6f94e79bbb4ce1d2300195e1cc1c87acd1f5422的提交遇到了同样的问题，但是不知道是否和本问题是同样的问题。

**Comment by Kaijun** [comment]
可能是你本地的hexo的环境有问题(不确定是npm包未成功安装 还是hexo版本等问题)
要是不熟悉hexo的话 最好clone整个项目, 我看你只是复制了theme, 因为整个主题还有一些自定义的页面在source里.
```
git clone https://github.com/Kaijun/hexo-theme-huxblog.git
cd hexo-theme-huxblog
npm install
```
然后再执行操作

我这边是没有问题的
![screen shot 2016-06-16 at 14 05 42](https://cloud.githubusercontent.com/assets/1693027/16116185/ba2c8a0c-33cb-11e6-9c37-40176d6093d2.png)

**Comment by Kaijun** [comment]
这个问题 e6f94e79bbb4ce1d2300195e1cc1c87acd1f5422 里确实修复了no-sidebar的情况, with sidebar的情况还没改, 你可以试下把报错的那行改成 `<%- page.content || body %>`

要是修复了的话 顺便给我提交个Pull Request 😄

**Comment by Kaijun** [comment]
不知道是因为hexo版本问题还是怎么样, 我这边无论是有没有sidebar的情况下, 都是可以成功创建page.

**Comment by lgyjg** [comment]
hi Kaijun
我尝试者修改了你给的patch，还是会抛出异常，昨天我就是这么修改的。
异常如下：
Unhandled rejection ReferenceError: /home/××/blog/test/themes/huxblog/layout/page.ejs:72
 >   70|                 post-container
    71|             ">
 \>\> 72|             <%- page.content || body %>
    73|             </div>
    74|     
    75|             <div class="

body is not defined
    at eval (eval at <anonymous> (/home/××/blog/test/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:3385)
    at eval (eval at <anonymous> (/home/××/blog/test/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:11622)
    at null._compiledSync (/home/××/blog/test/node_modules/ejs/lib/ejs.js:255:15)
    at tryCatcher (/home/××/blog/test/node_modules/bluebird/js/release/util.js:16:23)
    at null._compiled (/home/××/blog/test/node_modules/bluebird/js/release/method.js:15:34)
    at View.render (/home/××/blog/test/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/××/blog/test/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/××/blog/test/node_modules/bluebird/js/release/util.js:16:23)
    at /home/××/blog/test/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/××/blog/test/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:726:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)

同时也是依照以下命令安装的：
> git clone https://github.com/Kaijun/hexo-theme-huxblog.git
> cd hexo-theme-huxblog
> npm install

我觉得应该是其他问题导致，但是同样的代码在你哪儿无法复现，说明还是和hexo有关。

**Comment by lgyjg** [comment]
对了，Kaijun，我看你的验证是验证是否new 一个page的时候有问题，其实需要验证 hexo g时是否会有问题。以及在sever运行时，点击到该页面时会无相应，并抛出异常。

**Comment by Kaijun** [comment]
加了page.content || body 之后 有两种情况. 要么你在content不是空, 你的 Gallery/index.md 里要写上内容. 这样就可以了.
要么你在主题里加上其他模板 比如gallery.ejs, 然后基础模板是 page
```
---
layout: page
---
```
例子你可以参考 about.ejs

**Comment by Kaijun** [comment]
fixed 8f1881bae0a41fe302af8a2777b699af4c8fe5a3
